bookWebApi/bookWebApi/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

books/urls.py
from django.conf.urls import url
from . import views

app_name = 'books'
urlpatterns = [
    url(r'^$', views.book_list, name="list"),
    url(r'^create/$', views.book_create, name="create"),
    url(r'^requests/accept$', views.book_accept, name="accept"),
    url(r'^requests/reject$', views.book_reject, name="reject"),
    url(r'^remove/(?P<pk>\d+)/$', views.book_delete, name="remove_book"),
    url(r'^requests/$', views.book_requests, name="requests"),
    url('^search/', views.search_book, name='search'),
    url(r'^(?P<slug>[\w-]+)/$', views.book_details, name="details"),
]

reviews/urls.py
from django.conf.urls import url
from . import views

app_name = 'reviews'
urlpatterns = [
    url(r'^$', views.review_list, name="list"),
    url(r'^create/$', views.review_create, name="create"),
    url(r'^accept/$', views.accept_review, name="accept"),
    url(r'^reject/$', views.reject_review, name="reject"),
]

webBookApi/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.urls import path


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^books/', include('books.urls')),
    url(r'^reviews/', include('reviews.urls')),
    url(r'^role_requests/', include('role_requests.urls')),
    url(r'^authors/', include('authors.urls')),
    url(r'^about/$', views.about),
    url(r'^$', views.home),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^socials/', include('allauth.urls')),
    #won't redirect in accountsapp
    path('reset_password/', auth_views.PasswordResetView.as_view(), name="reset_password"),
    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(), name="password_reset_done"),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name="password_reset_confirm"),
    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(), name="password_reset_complete"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()
handler404 = "webBookApi.views.error_404"
handler500 = "webBookApi.views.error_500"

reviews/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MaxValueValidator, MinValueValidator, FileExtensionValidator
from general.models import AbstractEntity


class ReviewManager(models.Manager):
    def create_review(
            self,
            vote,
            review,
            book,
            user
    ):
        return self.create(
            vote = vote,
            review = review,
            book = book,
            user = user
        )


class Review(AbstractEntity):
    STATUS_PENDING = 0
    STATUS_REJECTED = 1
    STATUS_ACCEPTED = 2
    objects = ReviewManager()

    vote = models.IntegerField(default=0,
                               validators=[
                                   MaxValueValidator(5),
                                   MinValueValidator(0),
                               ])
    book = models.ForeignKey("books.Book", on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    review = models.CharField(max_length=30, default="None")
    status = models.IntegerField(default=STATUS_PENDING)
    upvotes = models.IntegerField(default=0)
    downvotes = models.IntegerField(default=0)

reviews/forms/review_form.py
from django import forms


class ReviewForm(forms.Form):

    placeholders = {
        'vote': 'Ocena',
        'review': 'Recenzja'
    }
    review = forms.CharField(max_length=255, widget=forms.Textarea(attrs={'rows': 3}))

    vote = forms.IntegerField()
    book_id = forms.IntegerField(widget=forms.NumberInput(attrs={'hidden': True}))

    def __init__(self, *args, book=None, **kwargs):
        super(ReviewForm, self).__init__(*args, **kwargs)
        self.fields['vote'].widget.attrs.update({'max': 5})
        self.fields['vote'].widget.attrs.update({'min': 1})

        if book:
            self.book = book
            self.fields['book_id'].initial = book.id

        for field in self.fields:
            self.fields[field].widget.attrs.update({
                'class': 'form-control w-100 mb-2',
            })

            if field in self.placeholders:
                self.fields[field].widget.attrs.update({
                    'placeholder': self.placeholders[field],
                })

reviews/views.py
from django.core.paginator import Paginator
from django.shortcuts import render
from books.models import Book
from reviews.models import Review
from django.http import HttpResponseRedirect
from .forms.review_form import ReviewForm
from .services import rating_service
from django.contrib import messages
from accounts.decorators import allowed_users, admin_only
from django.contrib.auth.decorators import login_required


@login_required(login_url='accounts:login')
@allowed_users(allowed_roles=['viewer', 'admin'])
def review_create(request):
    if request.method == 'POST':
        review_data = request.POST
        vote = int(review_data['vote'])

        if vote > 5 or vote < 0:
            messages.success(request, 'Oddany głos powinien mieścić się w przedziale od 1 do 5')
            return HttpResponseRedirect('/')

        review = Review.objects.create_review(
            vote,
            review_data['review'],
            Book.objects.get(id=review_data['book_id']),
            request.user
        )
        review.save()
        messages.success(request, 'Recenzja została dodana i oczekuje na akceptację')
        return HttpResponseRedirect('/')

    form = ReviewForm()
    return render(request, 'reviews/review_create.html', {'form': form})

@login_required(login_url='accounts:login')
@admin_only
def review_change_status(request, status):
    if request.method != 'POST':
        return HttpResponseRedirect('/')

    if status != Review.STATUS_PENDING and status != Review.STATUS_REJECTED and status != Review.STATUS_ACCEPTED:
        return HttpResponseRedirect('/')

    review = Review.objects.get(pk=request.POST['review_id'])

    review.status = status
    review.save()
    if review.status == Review.STATUS_ACCEPTED:
        rating_service.recalculate_book_rating(review.book)
        rating_service.recalculate_author_rating(review.book.authors.all())

    messages.success(request, 'Pomyslnie zmieniono status recenzji')
    return HttpResponseRedirect('/')


def accept_review(request):
    return review_change_status(request, Review.STATUS_ACCEPTED)


def reject_review(request):
    return review_change_status(request, Review.STATUS_REJECTED)

@login_required(login_url='accounts:login')
@admin_only
def review_list(request):
    p = Paginator(Review.objects.filter(status=Review.STATUS_PENDING), 10)
    page = request.GET.get('page')
    reviews = p.get_page(page)
    return render(request, 'reviews/review_list.html', {'reviews': reviews})

reviews/templates/reviews/review_create.html
<div class="card mt-4">
    <form method="post" class="card-body" action="{% url 'reviews:create' %}">
        <h4 class="mb-4">Dodaj recenzje</h4>
        {% csrf_token %}
        {{ form.vote }}
        {{ form.review }}
        <input type="number" value={{book.id}} id="book_id" name="book_id" hidden>
        <button type="submit" class="btn btn-success btn-lg mt-4" style="width: 200px;">Dodaj recenzje</button>
    </form>
</div>

reviews/templates/reviews/review_list.html
{% extends 'base_layout.html' %}

{% block content %}
    <h1 class="text-center mb-5">Recenzje czekające na akceptacje</h1>
        {% if not reviews %}
            <h3 class="mb-4">Brak nowych zgłoszeń</h3>
        {% endif %}

        {% for review in reviews %}
            <div class="mb-4">
                {% include "reviews/review_snippet.html" with review=review %}
            </div>
        {% endfor %}

    {% include "pagination.html" with items=reviews %}
{% endblock %}

reviews/templates/reviews/review_snippet.html
{% load has_group %}

<div class="my-3 card container">
    <div class="card-body d-flex row">
        <div class="col">
            <div class="row">
                <div class="col-10">
                    <p class="fs-5"><b>Użytkownik:</b> {{ review.user }}</p>
                    <p class="fs-5"><b>Treść:</b> {{ review.review }}</p>
                </div>
                <div class="col text-end">
                    <div class="col text-end">
                      {% include "review_stars.html" with rating=review.vote %}
                    </div>

                    {% if request.user|has_group:"admin" %}
                        <div class="mt-3">
                            <form method="post" action="{% url 'reviews:accept' %}">
                                {% csrf_token %}
                                <input type="number" value={{review.id}} id="review_id_1" name="review_id" hidden>
                                <button type="submit" class="btn btn-success btn-sm" style="width: 100px;">Zaakceptuj</button>
                            </form>
                            <form method="post" class="mt-2" action="{% url 'reviews:reject' %}">
                                {% csrf_token %}
                                <input type="number" value={{review.id}} id="review_id_2" name="review_id" hidden>
                                <button type="submit" class="btn btn-danger btn-sm" style="width: 100px;">Odrzuć</button>
                            </form>
                        </div>
                        {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>