authors/urls.py
from django.conf.urls import url
from django.urls import include
from . import views

app_name = 'authors'

urlpatterns = [
    url(r'^$', views.authors_list, name="list"),
    url(r'^create/$', views.authors_create, name="create"),
    url(r'^requests/$', views.author_requests, name="requests"),
    url(r'^remove/(?P<pk>\d+)/$', views.author_delete, name="remove_author"),
    url(r'^requests/accept$', views.author_accept, name="accept"),
    url(r'^requests/reject$', views.author_reject, name="reject"),
    url(r'^(?P<slug>[\w-]+)/$', views.author_details, name="details"),
]

bookWebApi/bookWebApi/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

books/urls.py
from django.conf.urls import url
from . import views

app_name = 'books'
urlpatterns = [
    url(r'^$', views.book_list, name="list"),
    url(r'^create/$', views.book_create, name="create"),
    url(r'^requests/accept$', views.book_accept, name="accept"),
    url(r'^requests/reject$', views.book_reject, name="reject"),
    url(r'^remove/(?P<pk>\d+)/$', views.book_delete, name="remove_book"),
    url(r'^requests/$', views.book_requests, name="requests"),
    url('^search/', views.search_book, name='search'),
    url(r'^(?P<slug>[\w-]+)/$', views.book_details, name="details"),
]

webBookApi/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.urls import path


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^books/', include('books.urls')),
    url(r'^reviews/', include('reviews.urls')),
    url(r'^role_requests/', include('role_requests.urls')),
    url(r'^authors/', include('authors.urls')),
    url(r'^about/$', views.about),
    url(r'^$', views.home),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^socials/', include('allauth.urls')),
    #won't redirect in accountsapp
    path('reset_password/', auth_views.PasswordResetView.as_view(), name="reset_password"),
    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(), name="password_reset_done"),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name="password_reset_confirm"),
    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(), name="password_reset_complete"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()
handler404 = "webBookApi.views.error_404"
handler500 = "webBookApi.views.error_500"

authors/models.py
from django.core.validators import FileExtensionValidator
from django.utils.text import slugify

from books.models import AbstractEntity
from books.models import models


class AuthorManager(models.Manager):
    def create_author(
            self,
            name,
            genre,
            description,
            birthDate,
            image
    ):
        author_slug = slugify(name)
        potential_slug_duplicate_len = len(self.filter(slug=author_slug))
        if potential_slug_duplicate_len > 0:
            author_slug += '-' + str(potential_slug_duplicate_len)

        author = self.create(
            name=name,
            description=description,
            birthDate=birthDate,
            rating=0,
            slug=author_slug,
            image=image,
        )
        author.genre.set([genre])
        return author


class Author(AbstractEntity):
    objects = AuthorManager()

    STATUS = (
        ("P", "Pending"),
        ("A", "Accepted"),
        ("R", "Rejected")
    )
    name = models.CharField(max_length=30, default="None")
    genre = models.ManyToManyField("books.Genre", related_name="genre")
    description = models.TextField(default="None")
    birthDate = models.DateField()
    slug = models.SlugField(default="None")
    rating = models.IntegerField(default=0)
    status = models.CharField(choices=STATUS, max_length=10, default="P")
    image = models.ImageField(
        default='author_images/default_author_1.jpg',
        upload_to='author_images',
        validators=[FileExtensionValidator(allowed_extensions=['jpg', 'png', 'jpeg'])]
    )

    def __str__(self):
        return self.name

    def snippet(self):
        return self.description[:50] + '...'

authors/forms/request_form.py
from django import forms


class AuthorRequestForm(forms.Form):
    placeholders = {
        'name': 'Imie i nazwisko',
        'description': 'Opis',
        'birthDate': 'Data urodzenia'
    }

    name = forms.CharField(
        max_length=200,
    )
    genre = forms.ChoiceField(
        choices=(),
    )
    description = forms.CharField(
        widget=forms.Textarea()
    )
    birthDate = forms.DateField(
        input_formats='%Y-%m-%d',
        widget=forms.DateInput(attrs={'type': 'date'})
    )
    slug = forms.CharField(
        max_length=100,
    )

    image = forms.ImageField()

    def __init__(self, *args, genre=None, **kwargs):
        super(AuthorRequestForm, self).__init__(*args, **kwargs)
        if genre:
            self.fields['genre'].choices = genre

        for field in self.fields:
            self.fields[field].widget.attrs.update({
                'class': 'form-control mb-2',
            })

            if field in self.placeholders:
                self.fields[field].widget.attrs.update({
                    'placeholder': self.placeholders[field],
                })

authors/forms/requests_list_form.py
from django import forms


class RequestListForm(forms.Form):
    author_id = forms.IntegerField(widget=forms.NumberInput(attrs={'hidden': True}))
    accept = forms.NullBooleanField()

    def __init__(self, *args, author=None, **kwargs):
        super(RequestListForm, self).__init__(*args, **kwargs)
        if author:
            self.author = author
            self.fields['author_id'].initial = author.id

authors/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, Http404
from django.shortcuts import render
from django.urls import reverse

from accounts.models import get_users
from authors.forms.request_form import AuthorRequestForm
from books.models import Genre
from general import mailing
from .forms.requests_list_form import RequestListForm
from .models import Author
from django.core.paginator import Paginator
from accounts.decorators import allowed_users, admin_only
from django.contrib import messages
from helpers.image_validator import validate_image


@login_required(login_url='accounts:login')
@allowed_users(allowed_roles=['viewer', 'admin'])
def authors_list(request):
    p = Paginator(Author.objects.all().filter(status='A').order_by('name'), 10)
    page = request.GET.get('page')
    authors = p.get_page(page)
    return render(request, 'authors/authors_list.html', {'authors': authors})


@login_required(login_url='accounts:login')
@allowed_users(allowed_roles=['viewer', 'admin'])
def author_details(request, slug):
    try:
        author = Author.objects.get(slug=slug, status="A")
    except:
        raise Http404()
    return render(request, 'authors/authors_details.html', {'author': author})


@login_required(login_url='accounts:login')
@admin_only
def author_delete(request, pk):
    if request.method == 'POST':
        author = Author.objects.get(pk=pk)
        author.delete()
        messages.success(request, "Pomyslnie usunieto autora")

        return HttpResponseRedirect("/authors/")


@login_required(login_url='accounts:login')
@allowed_users(allowed_roles=['viewer', 'admin'])
def authors_create(request):
    if request.method == 'POST':
        authors_data = request.POST

        genre = Genre.objects.get(pk=int(authors_data['genre']))
        if not validate_image(request.FILES['image']):
            messages.success(request, "Zły format obrazka, spróbuj ponownie")
            return HttpResponseRedirect('/')

        new_author = Author.objects.create_author(
            authors_data['name'],
            genre,
            authors_data['description'],
            authors_data['birthDate'],
            request.FILES['image']
        )

        new_author.save()

        recipients = get_users('admin')
        mailing.send_mails('New Author Added', 'Hi, New item added to your request list \nhttp://127.0.0.1:8000/authors/requests/', recipients)

        return HttpResponseRedirect('/')


    genre_options = []
    for genre in Genre.objects.all():
        genre_options.append((genre.id, genre.__str__()))

    form = AuthorRequestForm(genre=genre_options)
    return render(request, 'authors/authors_create.html', {'form': form})


@login_required(login_url='accounts:login')
@admin_only
def author_requests(request):
    forms = []
    for author in Author.objects.filter(status='P'):
        forms.append(RequestListForm(author=author))
    p = Paginator(forms, 10)
    page = request.GET.get('page')
    forms = p.get_page(page)

    return render(request, 'authors/author_requests.html', {'forms': forms})


@login_required(login_url='accounts:login')
@admin_only
def author_accept(request):
    if request.method == 'POST':
        author_id = request.POST['author_id']
        author = Author.objects.get(pk=author_id)
        author.status = 'A'
        author.save()
        author_status_change_message(request)

    recipients = get_users('viewer')
    mailing.send_mails('New Author has been added', 'Hi, Author: ' + author.name + ' was approved. Go to BookWeb and check it now \nhttp://127.0.0.1:8000/books/', recipients)

    return HttpResponseRedirect(reverse('authors:requests'))


@login_required(login_url='accounts:login')
@admin_only
def author_reject(request):
    if request.method == 'POST':
        author_id = request.POST['author_id']
        author = Author.objects.get(pk=author_id)
        author.status = 'R'
        author.save()
        author_status_change_message(request)

    return HttpResponseRedirect(reverse('authors:requests'))


def author_status_change_message(request):
    messages.success(request, 'Pomyslnie zmieniono status autora')

authors/templates/authors/author_requests.html
{% extends 'base_layout.html' %}

{% block content %}
    <h1 class="text-center mb-5">Autorzy czekające na akceptacje</h1>
        {% if not forms %}
            <h3 class="mb-4">Brak nowych zgłoszeń</h3>
        {% endif %}

        {% for form in forms %}
            <div class="mb-4">
                {% include "authors/author_snippet.html" with author=form.author author_request=True %}
            </div>
        {% endfor %}

        {% include "pagination.html" with items=forms %}
{% endblock %}

authors/templates/authors/author_snippet.html
{% load has_group %}

<div class="my-3 card container">
    <div class="card-body d-flex row">
        <div class="col-2">
            <div class="w-100 h-100">
                 <img class="img-thumbnail" src="{{ author.image.url }}" alt="author-image">
            </div>
        </div>
        <div class="col-10">
            <div class="row">
                <div class="col-10">
                    <h2>


                        {% if not author_request %}
                        <a class="text-decoration-none link-secondary" href="{% url 'authors:details' slug=author.slug %}">
                            {{ author.name }} {{ author.surname }}
                        </a>
                        {% endif %}

                        {% if author_request %}
                        <span>
                            {{ author.name }} {{ author.surname }}
                        </span>
                        {% endif %}
                    </h2>
                    <p>{{ author.description }}</p>
                </div>
                <div class="col text-end">
                    <p>{{ author.birthDate|date:"d.m.Y" }}</p>

                    <div class="col text-end">
                        {% include "review_stars.html" with rating=author.rating %}
                    </div>

                     {% if request.user|has_group:"admin" and not author_request %}
                        <div class="mt-3">
                            <form method="POST" action="{% url 'authors:remove_author' pk=author.pk %}">
                                {% csrf_token %}
                                <button class="btn btn-danger">Usuń</button>
                            </form>
                        </div>
                     {% endif %}




                     {% if request.user|has_group:"admin" and author_request %}
                        <div class="mt-3">
                            <form method="post" action="{% url 'authors:accept' %}">
                                {% csrf_token %}
                                {{form.author_id}}
                                <button type="submit" class="btn btn-success btn-sm" style="width: 100px;">Zaakceptuj</button>
                            </form>
                            <form method="post" class="mt-2" action="{% url 'authors:reject' %}">
                                {% csrf_token %}
                                {{form.author_id}}
                                <button type="submit" class="btn btn-danger btn-sm" style="width: 100px;">Odrzuć</button>
                            </form>
                        </div>
                     {% endif %}

                </div>
            </div>
        </div>
    </div>
</div>

authors/templates/authors/authors_create.html
{% extends 'base_layout.html' %}

{% block content %}
    <h1 class="text-center mb-5">Dodaj nowego autora</h1>
    <form method="post" action="{% url 'authors:create' %}" enctype="multipart/form-data">
        {% csrf_token %}

        {{form.name}}

        {{form.genre}}

        {{form.description}}

        {{form.birthDate}}


        {{ form.image }}
        <button type="submit" class="btn btn-success">Zgłoś</button>
    </form>
{% endblock %}

authors/templates/authors/authors_details.html
{% extends 'base_layout.html' %}

{% block content %}
    <h1 class="text-center mb-5">Autor: {{author.name}} {{author.surname}}</h1>

<div class="book-detail">
    <div class="book card">
            <div class="card-body">

                <div class="row">
                    <div class="col-2">
                        <div class="w-100 h-100">
                            <img class="img-thumbnail" src="{{ author.image.url }}" alt="author-image">
                        </div>
                    </div>

                    <div class="col">
                        <div class="row">
                            <h2 class="col">{{author.name}} {{author.surname}}</h2>

                            <div class="col-2 mt-2 fs-5 text-end">
                                {% include "review_stars.html" with rating=author.rating %}
                            </div>
                        </div>

                        <h5>{{ author.birthDate|date:"d.m.Y" }}</h5>
                    </div>
                </div>
                <div class="mt-5">
                    <p>{{ author.description }}</p>
                </div>
            </div>
    </div>
</div>
{% endblock %}

authors/templates/authors/authors_list.html
{% extends 'base_layout.html' %}

{% block content %}
    <h1 class="text-center mb-5">Lista autorów</h1>

    {% for author in authors %}
        <div class="w-100">
            {% include "authors/author_snippet.html" with author=author %}
        </div>

    {% endfor %}

    {% include "pagination.html" with items=authors %}
{% endblock %}