accounts/urls.py
from django.conf.urls import url
from django.urls import path
from .import views
from django.contrib.auth import views as auth_views

app_name = 'accounts'

urlpatterns = [
    url(r'^signup/$', views.signup_view, name="signup"),
    url(r'^login/$', views.login_view, name="login"),
    url(r'^logout/$', views.logout_view, name="logout"),
    url(r'^profile/$', views.user_profile_view, name="profile"),
    url(r'^profile/update/$', views.UpdateUser_profile_view, name="profileUpdate"),
]

authors/urls.py
from django.conf.urls import url
from django.urls import include
from . import views

app_name = 'authors'

urlpatterns = [
    url(r'^$', views.authors_list, name="list"),
    url(r'^create/$', views.authors_create, name="create"),
    url(r'^requests/$', views.author_requests, name="requests"),
    url(r'^remove/(?P<pk>\d+)/$', views.author_delete, name="remove_author"),
    url(r'^requests/accept$', views.author_accept, name="accept"),
    url(r'^requests/reject$', views.author_reject, name="reject"),
    url(r'^(?P<slug>[\w-]+)/$', views.author_details, name="details"),
]

bookWebApi/bookWebApi/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

books/urls.py
from django.conf.urls import url
from . import views

app_name = 'books'
urlpatterns = [
    url(r'^$', views.book_list, name="list"),
    url(r'^create/$', views.book_create, name="create"),
    url(r'^requests/accept$', views.book_accept, name="accept"),
    url(r'^requests/reject$', views.book_reject, name="reject"),
    url(r'^remove/(?P<pk>\d+)/$', views.book_delete, name="remove_book"),
    url(r'^requests/$', views.book_requests, name="requests"),
    url('^search/', views.search_book, name='search'),
    url(r'^(?P<slug>[\w-]+)/$', views.book_details, name="details"),
]

reviews/urls.py
from django.conf.urls import url
from . import views

app_name = 'reviews'
urlpatterns = [
    url(r'^$', views.review_list, name="list"),
    url(r'^create/$', views.review_create, name="create"),
    url(r'^accept/$', views.accept_review, name="accept"),
    url(r'^reject/$', views.reject_review, name="reject"),
]

role_requests/urls.py
from django.conf.urls import url
from .import views

app_name = 'role_requests'

urlpatterns = [
    url(r'^$', views.role_request_list, name="list"),
    url(r'^create/$', views.role_request_create, name="create"),
    url(r'^accept/$', views.accept_role_request, name="accept"),
    url(r'^reject/$', views.reject_role_request, name="reject"),
]

webBookApi/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.urls import path


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^books/', include('books.urls')),
    url(r'^reviews/', include('reviews.urls')),
    url(r'^role_requests/', include('role_requests.urls')),
    url(r'^authors/', include('authors.urls')),
    url(r'^about/$', views.about),
    url(r'^$', views.home),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^socials/', include('allauth.urls')),
    #won't redirect in accountsapp
    path('reset_password/', auth_views.PasswordResetView.as_view(), name="reset_password"),
    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(), name="password_reset_done"),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name="password_reset_confirm"),
    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(), name="password_reset_complete"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()
handler404 = "webBookApi.views.error_404"
handler500 = "webBookApi.views.error_500"

templates/about.html
{% extends "base_layout.html" %}

{% block content %}

<div class="content">
    <div class="card">
        <div class="card-body">
            <h1 class="mb-5 text-center">O serwisie</h1>
            <p class="card-text">
                BookWeb to serwis internetowy pozwalający poznawać nowe książki oraz je recenzować. Serwis jest zbiorem wszystkich książek, dzięki czemu internauci
                są w stanie szybko przeczytać "zajawkę" i zobaczyć czy chcą wgłębić się w powieść, a następnie ją ocenić dzieląc się przemyśleniami z innymi użytkownikami.
            </p>
            <p>
                Funkcjonalności:
                <ul>
                    <li>przeglądanie książek,</li>
                    <li>zgłaszanie nowych książek,</li>
                    <li>dodawanie recenzji książek,</li>
                    <li>przeglądanie recenzji książek,</li>
                    <li>przeglądanie autorów.</li>
                </ul>
            </p>

            <h2 class="my-5 text-center">Projekt</h2>
            <div class="row justify-content-center">
                <div class="col-4">
                     <div class="card text-white text-center bg-dark mb-3">
                        <div class="card-body">
                            <h5 class="card-title">Projekt</h5>
                            <a href="https://github.com/users/musialpatryk/projects/3" class="card-link link-info">Github project</a>
                        </div>
                     </div>
                 </div>
                 <div class="col-4">
                     <div class="card text-white text-center bg-dark mb-3">
                        <div class="card-body">
                            <h5 class="card-title">Repozytorium</h5>
                            <a href="https://github.com/musialpatryk/web-book" class="card-link link-info">Github</a>
                        </div>
                     </div>
                 </div>
             </div>

            <h2 class="mt-5 mb-4 text-center">Twórcy</h2>
            <div class="row">
                 <div class="col-sm-3">
                    <div class="card-body bg-secondary text-light" style="margin: 10px; text-align:center;">
                        <h5 class="card-title">Dawid Rusiłowski</h5>
                        <a href="https://github.com/NURSAA" class="card-link link-dark">Github</a>
                    </div>
                 </div>
                <div class="col-sm-3">
                    <div class="card-body bg-secondary text-light" style="margin: 10px; text-align:center;">
                        <h5 class="card-title">Mariusz Przybyła</h5>
                        <a href="https://github.com/PrzybylaM" class="card-link link-dark">Github</a>
                    </div>
                 </div>
                <div class="col-sm-3">
                    <div class="card-body bg-secondary text-light" style="margin: 10px; text-align:center;">
                        <h5 class="card-title">Musiał Patryk</h5>
                        <a href="https://github.com/musialpatryk" class="card-link link-dark">Github</a>
                    </div>
                 </div>
                <div class="col-sm-3">
                    <div class="card-body bg-secondary text-light" style="margin: 10px; text-align:center;">
                        <h5 class="card-title">Mikołaj Porębski</h5>
                        <a href="https://github.com/ViciousCabaret" class="card-link link-dark">Github</a>
                    </div>
                 </div>
             </div>


            <h2 class="my-5 text-center">Wykorzystane technologie</h2>
            <div class="d-flex justify-content-center mb-5">
                <div class="row">
                    <div class="col-sm-4">
                        <div class="card text-white bg-dark mb-3" style="max-width: 18rem; margin: 10px; text-align:center;">
                            <div class="card-body">
                                <h5 class="card-title">HTML</h5>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-4">
                        <div class="card text-white bg-dark mb-3" style="max-width: 18rem; margin: 10px; text-align:center;">
                            <div class="card-body">
                                <h5 class="card-title">CSS</h5>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-4">
                        <div class="card text-white bg-dark mb-3" style="max-width: 18rem; margin: 10px; text-align:center;">
                            <div class="card-body">
                                <h5 class="card-title">Python</h5>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-4">
                        <div class="card text-white bg-dark mb-3" style="max-width: 18rem; margin: 10px; text-align:center;">
                            <div class="card-body">
                                <h5 class="card-title">Django</h5>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-4">
                        <div class="card text-white bg-dark mb-3" style="max-width: 18rem; margin: 10px; text-align:center;">
                            <div class="card-body">
                                <h5 class="card-title">BOOTSTRAP</h5>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-4">
                        <div class="card text-white bg-dark mb-3" style="max-width: 18rem; margin: 10px; text-align:center;">
                            <div class="card-body">
                                <h5 class="card-title">SqlLite</h5>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>
{% endblock %}

templates/base_layout.html
{% load static %}
{% load has_group %}
<!DOCTYPE html>
<html>
    <head>
    <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
        <title>BookWeb</title>
        <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
        <link rel="stylesheet" href="{% static 'style.css' %}">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        <script src="{% static 'fontawesomefree/js/all.min.js' %}"></script>
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    </head>
    <body>

    {% if request.user.is_authenticated %}
     <nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-5">
      <div class="container">
        <a class="navbar-brand brand-name" href="/">BookWeb</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarText">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">

             <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle"
                     id="bookDropdown"
                     role="button"
                     data-bs-toggle="dropdown"
                     aria-expanded="false">
                    Książki
                  </a>
                  <ul class="dropdown-menu" aria-labelledby="bookDropdown">
                    <li>
                      <a class="dropdown-item" href="{% url 'books:list' %}">Lista książek</a>
                    </li>
                    <li>
                      <a class="dropdown-item" href="{% url 'books:create' %}">Dodaj książke</a>
                    </li>
                  </ul>
             </li>

             <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle"
                     id="authorsDropdown"
                     role="button"
                     data-bs-toggle="dropdown"
                     aria-expanded="false">
                    Autorzy
                  </a>
                  <ul class="dropdown-menu" aria-labelledby="bookDropdown">
                    <li>
                      <a class="dropdown-item" href="{% url 'authors:list' %}">Lista autorów</a>
                    </li>
                    <li>
                      <a class="dropdown-item" href="{% url 'authors:create' %}">Dodaj autora</a>
                    </li>
                  </ul>
             </li>
            <li class="nav-item">
              <a class="nav-link" href="/about">O serwisie</a>
            </li>

            {% if not request.user|has_group:"admin" %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'role_requests:create' %}">Aplikuj na moderatora</a>
            </li>
            {% endif %}

              {% if request.user|has_group:"admin" %}
              <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle"
                     id="adminDropdown"
                     role="button"
                     data-bs-toggle="dropdown"
                     aria-expanded="false">
                    Administracja
                  </a>
                  <ul class="dropdown-menu" aria-labelledby="adminDropdown">
                    <li>
                      <a class="dropdown-item" href="{% url 'books:requests' %}">Książki do akceptacji</a>
                    </li>
                    <li>
                      <a class="dropdown-item" href="{% url 'reviews:list' %}">Recenzje do akceptacji</a>
                    </li>
                    <li>
                      <a class="dropdown-item" href="{% url 'authors:requests' %}">Autorzy do akceptacji</a>
                    </li>
                    <li>
                      <a class="dropdown-item" href="{% url 'role_requests:list' %}">Podania o moderatora</a>
                    </li>
                  </ul>
             </li>
             {% endif %}
          </ul>

          {% include "search_bar.html" %}

        <div class="navbar-login-control ms-4 dropdown">
              <button class="btn btn-dark dropdown-toggle" style="min-width: 160px"
                 id="dropdownMenuLink"
                 data-toggle="dropdown"
                 aria-haspopup="true"
                 aria-expanded="false">
                  Konto <i class="fas fa-user-circle"></i>
              </button>

              <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="dropdownMenuLink">
                  {% if not request.user.is_authenticated %}
                    <li>
                        <form action="{% url 'accounts:login' %}" class="dropdown-item" method="get">
                            {% csrf_token %}
                            <button type="submit" class="dropdown-item">Login</button>
                        </form>
                        <div class="dropdown-divider"></div>
                        <form action="{% url 'accounts:signup' %}" method="get">
                            {% csrf_token %}
                            <button type="submit" class="dropdown-item">SignUp</button>
                        </form>
                    </li>
                {% endif %}


                  {% if request.user.is_authenticated %}
                    <li>
                        <form action="{% url 'accounts:profile' %}" method="post">
                            {% csrf_token %}
                            <button type="submit" class="dropdown-item">Profil użytkownika</button>
                        </form>
                        <div class="dropdown-divider"></div>
                        <form action="{% url 'accounts:logout' %}" method="post">
                            {% csrf_token %}
                            <button type="submit" class="dropdown-item">Wyloguj</button>
                        </form>
                    </li>
                {% endif %}
              </ul>
        </div>

        </div>
      </div>
    </nav>
    {% endif %}

    <div class="main-content">
        <div class="container {% if not request.user.is_authenticated %}not-logged{% endif %}">
            {% block content %}
            {% endblock %}
        </div>

        {% block full_width_content %}
        {% endblock %}
    </div>

    {% if request.user.is_authenticated %}
        {% include "footer.html" %}
    {% endif %}

    {% for msg in messages %}
    <div class="message-container">
         <div class="alert alert-warning alert-dismissible" role="alert">
            <h5 class="alert-heading text-center">{{msg}}</h5>
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
     </div>
    {% endfor %}

    <script src="{% static 'js/bootstrap.js' %}"></script>
    </body>
</html>

templates/carousel.html
{% block content %}
<div id="{{name}}" class="carousel slide" data-bs-ride="carousel">
    <div class="carousel-indicators">
        {% for list_element in books %}
            {% if forloop.first %}
                <button type="button"
                        data-bs-target="#{{name}}"
                        data-bs-slide-to="{{ forloop.counter0 }}"
                        class="active"
                        aria-current="true"
                        aria-label="Slide {{ forloop.counter0 }}">
                </button>
            {% else %}
                <button type="button"
                        data-bs-target="#{{name}}"
                        data-bs-slide-to="{{ forloop.counter0 }}"
                        aria-label="Slide {{ forloop.counter0 }}">
                </button>
            {% endif %}

        {% endfor %}
    </div>
    <div class="carousel-inner">

        {% for book in books %}
            {% if forloop.first %}
            <div class="carousel-item active">
            {% else %}
            <div class="carousel-item">
            {% endif %}
                <a href="{% url 'books:details' slug=book.slug %}">
                    <div class="carousel-img-container w-100 h-100">
                        <img src="/assets/media/{{book.image}}" class="carousel-img" alt="{{book}}">
                    </div>
                    <div class="carousel-caption d-none d-md-block">
                        <h3>{{book}}</h3>
                    </div>
                </a>
            </div>
        {% endfor %}

    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#{{name}}" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#{{name}}" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
    </button>
</div>
{% endblock %}

templates/footer.html
<!-- Footer -->
<footer class="text-center text-lg-start bg-light text-muted mt-4">

  <section class="bg-dark text-light py-3">
    <div class="container text-center text-md-start mt-5">
      <div class="row mt-3">
        <div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">
          <h6 class="text-uppercase fw-bold mb-4">
            <i class="fas fa-gem me-3"></i>BookWeb App
          </h6>
          <p>
            BookWeb to serwis internetowy pozwalający poznawać nowe książki oraz je recenzować. Serwis jest zbiorem wszystkich książek, dzięki czemu internauci są w stanie szybko przeczytać "zajawkę" i zobaczyć czy chcą wgłębić się w powieść, a następnie ją ocenić dzieląc się przemyśleniami z innymi użytkownikami.
          </p>
        </div>

        <div class="col-md-4 col-lg-4 col-xl-4 mx-auto mb-4">
          <h6 class="text-uppercase fw-bold mb-4">
            Wykorzystane technologie
          </h6>
          <ul>
            <li>Python</li>
            <li>Django</li>
            <li>Bootstrap</li>
          </ul>
        </div>

        <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4">
          <p>
            <a href="/" class="link-light text-decoration-none">Strona główna</a>
          </p>
          <p>
            <a href="books/" class="link-light text-decoration-none">Książki</a>
          </p>
          <p>
            <a href="authors/" class="link-light text-decoration-none">Autorzy</a>
          </p>
          <p>
            <a href="about/" class="link-light text-decoration-none">O serwisie</a>
          </p>
        </div>
    </div>
  </section>

</footer>

templates/homepage.html
{% extends "base_layout.html" %}

{% block full_width_content %}
<div class="home-page-container text-center">
    <div class="carousel-container">
        <h2 class="mb-5">Polecane na dzisiaj</h2>
        <div class="container">
            {% include "carousel.html" with name='today_list' books=today_list %}
        </div>
    </div>

    <div class="carousel-container">
        <h2 class="pt-5 mb-5">Znajdź coś dla siebie</h2>
        <div class="container">
            {% include "carousel.html" with name='random_list' books=random_list %}
        </div>
    </div>

    <div class="carousel-container">
        <h2 class="pt-3 mb-5">Najchętniej oceniane</h2>
        <div class="container">
            {% include "carousel.html" with name='most_rated_list' books=most_rated_list %}
        </div>
    </div>

    <div class="carousel-container">
        <h2 class="pt-3 mb-5">Top 3 najlepiej ocenianych</h2>
        <div class="container">
            {% include "carousel.html" with name='top_books_list' books=top_books_list %}
        </div>
    </div>

    <div class="carousel-container">
        <h2 class="pt-3 mb-5">Nowo dodane</h2>
        <div class="container">
            {% include "carousel.html" with name='new_books_list' books=new_books_list %}
        </div>
    </div>
</div>



{% endblock %}

templates/pagination.html
<div>
    {% if items.has_previous %}
        <a href="?page=1">
            <button type="button" class="btn btn-secondary">
                &laquo Pierwsza
            </button>
        </a>
        <a href="?page={{ items.previous_page_number }}">
            <button type="button" class="btn btn-secondary">
                Poprzednia
            </button>
        </a>
    {% endif %}

    <div class="btn btn-secondary disabled">
        Strona {{ items.number }} z {{ items.paginator.num_pages }}
    </div>

    {% if items.has_next %}
        <a href="?page={{ items.next_page_number }}">
            <button type="button" class="btn btn-secondary">
                Następna
            </button>
        </a>
        <a href="?page={{ items.paginator.num_pages }}">
            <button type="button" class="btn btn-secondary">
                Ostatnia &raquo
            </button>
        </a>
    {% endif %}
</div>

templates/review_stars.html
<span class="fa fa-star btn-rating {% if rating >= 1 %} checked {% endif %}}}"></span>
<span class="fa fa-star btn-rating {% if rating >= 2 %} checked {% endif %}"></span>
<span class="fa fa-star btn-rating {% if rating >= 3 %} checked {% endif %}"></span>
<span class="fa fa-star btn-rating {% if rating >= 4 %} checked {% endif %}"></span>
<span class="fa fa-star btn-rating {% if rating >= 5 %} checked {% endif %}"></span>

templates/search_bar.html
<form class="d-flex my-2" action="{% url 'books:search' %}" method="get">
  <input class="form-control me-2" name="search" type="text" placeholder="Szukaj..."/>
  <button type="submit" class="btn btn-outline-secondary">Szukaj</button>
</form>

templates/searched_items.html
{% extends 'base_layout.html' %}

{% block content %}

    {% if books %}
        <h1 class="text-center mb-5">Wyszukane książki</h1>
        <div class="books">
            {% for book in books %}
                {% include "books/book_snippet.html" with book=book %}
            {% endfor %}
        </div>
    {% endif %}
    <br/>
    {% if authors %}
        <h1 class="text-center mb-5">Wyszukani autorzy</h1>
        <div class="books">
            {% for author in authors %}
                {% include "authors/author_snippet.html" with author=author %}
            {% endfor %}
        </div>
    {% endif %}

{% endblock %}