bookWebApi/bookWebApi/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

books/urls.py
from django.conf.urls import url
from . import views

app_name = 'books'
urlpatterns = [
    url(r'^$', views.book_list, name="list"),
    url(r'^create/$', views.book_create, name="create"),
    url(r'^requests/accept$', views.book_accept, name="accept"),
    url(r'^requests/reject$', views.book_reject, name="reject"),
    url(r'^remove/(?P<pk>\d+)/$', views.book_delete, name="remove_book"),
    url(r'^requests/$', views.book_requests, name="requests"),
    url('^search/', views.search_book, name='search'),
    url(r'^(?P<slug>[\w-]+)/$', views.book_details, name="details"),
]

webBookApi/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.urls import path


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^books/', include('books.urls')),
    url(r'^reviews/', include('reviews.urls')),
    url(r'^role_requests/', include('role_requests.urls')),
    url(r'^authors/', include('authors.urls')),
    url(r'^about/$', views.about),
    url(r'^$', views.home),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^socials/', include('allauth.urls')),
    #won't redirect in accountsapp
    path('reset_password/', auth_views.PasswordResetView.as_view(), name="reset_password"),
    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(), name="password_reset_done"),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name="password_reset_confirm"),
    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(), name="password_reset_complete"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()
handler404 = "webBookApi.views.error_404"
handler500 = "webBookApi.views.error_500"

books/models.py
from django.utils.text import slugify

from general.models import AbstractEntity
from django.db import models
from authors.models import Author
from django.contrib.auth.models import User
from django.core.validators import FileExtensionValidator

from helpers.random_photo import get_random_photo


class Genre(AbstractEntity):
    genreName = models.CharField(max_length=30, default="None")
    slug = models.CharField(max_length=30, default="None")

    def __str__(self):
        return self.genreName


class BookManager(models.Manager):
    def create_book(
            self,
            title,
            description,
            author,
            genre,
            publishDate,
            image
    ):
        book_slug = slugify(title)
        potential_slug_duplicate_len = len(self.filter(slug=book_slug))
        if potential_slug_duplicate_len > 0:
           book_slug += '-' + str(potential_slug_duplicate_len)

        book = self.create(
            title=title,
            description=description,
            pages=2,
            rating=0,
            slug=book_slug,
            publishDate=publishDate,
            image=image
        )
        book.authors.set([author])
        book.genre.set([genre])
        return book


class Book(AbstractEntity):
    objects = BookManager()

    STATUS = (
        ("P", "Pending"),
        ("A", "Accepted"),
        ("R", "Rejected")
    )
    authors = models.ManyToManyField(Author)
    title = models.CharField(max_length=100, default="None")
    description = models.TextField(default="None")
    genre = models.ManyToManyField(Genre)
    rating = models.IntegerField(default=0)
    pages = models.IntegerField(default=None)
    slug = models.SlugField(max_length=100)
    publishDate = models.DateTimeField(null=True, blank=True)
    status = models.CharField(choices=STATUS, max_length=10, default="P")
    image = models.ImageField(
        default='book_images/default_book_1.jpg',
        upload_to='book_images',
        validators=[FileExtensionValidator(allowed_extensions=['jpg', 'png', 'jpeg'])]
    )

    def __str__(self):
        return self.title

    def snippet(self):
        return self.description[:50] + '...'


class FavoriteBooks(AbstractEntity):
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)


# Optional


class Series(AbstractEntity):
    name = models.CharField(max_length=30, default="None")
    authors = models.ManyToManyField(Author)
    book = models.ManyToManyField(Book)
    description = models.TextField(default="None")
    rating = models.FloatField(default=None)

books/forms/request_form.py
from django import forms


class BookRequestForm(forms.Form):
    placeholders = {
        'title': 'Tytuł',
        'description': 'Opis',
        'publishDate': 'Data publikacji'
    }

    title = forms.CharField(
        max_length=100,
    )
    author = forms.ChoiceField(
        choices=(),
    )
    genre = forms.ChoiceField(
        choices=(),
    )
    description = forms.CharField(
        widget=forms.Textarea()
    )
    publishDate = forms.DateField(
        input_formats='%Y-%m-%d',
        widget=forms.DateInput(attrs={'type': 'date'})
    )
    image = forms.ImageField()

    def __init__(self, *args, authors=None, genre=None, **kwargs):
        super(BookRequestForm, self).__init__(*args, **kwargs)
        if authors:
            self.fields['author'].choices = authors

        if genre:
            self.fields['genre'].choices = genre

        for field in self.fields:
            self.fields[field].widget.attrs.update({
                'class': 'form-control mb-2',
            })

            if field in self.placeholders:
                self.fields[field].widget.attrs.update({
                    'placeholder': self.placeholders[field],
                })

books/forms/requests_list_form.py
from django import forms


class RequestListForm(forms.Form):
    book_id = forms.IntegerField(widget=forms.NumberInput(attrs={'hidden': True}))
    accept = forms.NullBooleanField()

    def __init__(self, *args, book=None, **kwargs):
        super(RequestListForm, self).__init__(*args, **kwargs)
        if book:
            self.book = book
            self.fields['book_id'].initial = book.id

books/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, Http404
from django.shortcuts import render
from django.urls import reverse

from helpers.search import books_full_search, authors_full_search
from reviews.models import Review
from .forms.request_form import BookRequestForm
from .forms.requests_list_form import RequestListForm
from .models import Genre
from django.core.paginator import Paginator
from reviews.forms.review_form import ReviewForm
from authors.models import Author
from general import mailing
from .models import Book
from accounts.decorators import allowed_users, admin_only
from accounts.models import get_users
from django.contrib import messages
from helpers.image_validator import validate_image


@login_required(login_url='accounts:login')
@allowed_users(allowed_roles=['viewer', 'admin'])
def book_list(request):
    p = Paginator(Book.objects.filter(status='A').order_by('publishDate'), 10)
    page = request.GET.get('page')
    books = p.get_page(page)
    return render(request, 'books/book_list.html', {'books': books})


@login_required(login_url='accounts:login')
@allowed_users(allowed_roles=['viewer', 'admin'])
def book_details(request, slug):
    try:
        book = Book.objects.get(slug=slug, status = 'A')
    except:
        raise Http404()

    display_reviews = Review.objects.filter(status=Review.STATUS_ACCEPTED, book=book).order_by('-vote')

    form = ReviewForm()
    return render(request, 'books/book_details.html', {'book': book, 'form': form, 'display_reviews': display_reviews})


@login_required(login_url='accounts:login')
@allowed_users(allowed_roles=['viewer', 'admin'])
def book_create(request):
    if request.method == 'POST':
        book_data = request.POST

        author = Author.objects.get(pk=int(book_data['author']))
        genre = Genre.objects.get(pk=int(book_data['genre']))
        if not validate_image(request.FILES['image']):
            messages.success(request, "Zły format obrazka, spróbuj ponownie")
            return HttpResponseRedirect('/')

        new_book = Book.objects.create_book(
            book_data['title'],
            book_data['description'],
            author,
            genre,
            book_data['publishDate'],
            request.FILES['image']
        )

        new_book.save()

        recipients = get_users('admin')
        mailing.send_mails('New Book Added', 'Hi, New item added to your request list \nhttp://127.0.0.1:8000/books/requests/', recipients)

        return HttpResponseRedirect('/')

    author_options = []
    for author in Author.objects.all():
        author_options.append((author.id, author.__str__()))

    genre_options = []
    for genre in Genre.objects.all():
        genre_options.append((genre.id, genre.__str__()))

    form = BookRequestForm(authors=author_options, genre=genre_options)
    return render(request, 'books/book_create.html', {'form': form})


@login_required(login_url='accounts:login')
@admin_only
def book_requests(request):
    forms = []
    for book in Book.objects.filter(status='P').order_by('-publishDate'):
        forms.append(RequestListForm(book=book))
    p = Paginator(forms, 10)
    page = request.GET.get('page')
    forms = p.get_page(page)

    return render(request, 'books/book_requests.html', {'forms': forms})


@login_required(login_url='accounts:login')
@admin_only
def book_accept(request):
    if request.method == 'POST':
        book_id = request.POST['book_id']
        book = Book.objects.get(pk=book_id)
        book.status = 'A'
        book.save()
        book_status_change_message(request)

    recipients = get_users('viewer')
    mailing.send_mails('New Book has been added', 'Hi, Book: ' + book.title + ' was approved. Go to BookWeb and check it now \nhttp://127.0.0.1:8000/books/', recipients)

    return HttpResponseRedirect(reverse('books:requests'))


@login_required(login_url='accounts:login')
@admin_only
def book_reject(request):
    if request.method == 'POST':
        book_id = request.POST['book_id']
        book = Book.objects.get(pk=book_id)
        book.status = 'R'
        book.save()
        book_status_change_message(request)

    return HttpResponseRedirect(reverse('books:requests'))


def book_status_change_message(request):
    messages.success(request, 'Pomyslnie zmieniono status ksiazki')


@login_required(login_url='accounts:login')
@admin_only
def book_delete(request, pk):
    if request.method == 'POST':
        book = Book.objects.get(pk=pk)
        book.delete()
        messages.success(request, 'Pomyslnie usunieto ksiazke')
        return HttpResponseRedirect("/books/")


@login_required(login_url='accounts:login')
@allowed_users(allowed_roles=['viewer', 'admin'])
def search_book(request):
    search_text = request.GET.get("search")

    if search_text is None:
        return render(request, 'books/book_not_found.html', {'name': '""'})

    books = books_full_search(search_text)
    authors = authors_full_search(search_text)

    if len(books) == 0 and len(authors) == 0:
        return render(request, 'books/book_not_found.html', {'name': search_text})

    return render(request, 'searched_items.html', {'books': books, 'authors': authors})

books/templates/books/book_create.html
{% extends 'base_layout.html' %}

{% block content %}
    <h1 class="text-center mb-5">Dodaj nową książke</h1>
    <form method="post" action="{% url 'books:create' %}" enctype="multipart/form-data">
        {% csrf_token %}

        {{form.title}}

        {{form.author}}
        {{form.genre}}

        {{form.description}}

        {{form.publishDate}}

        {{form.image}}
        <button type="submit" class="btn btn-lg btn-success mt-4">Zgłoś prośbę o dodanie</button>
    </form>
{% endblock %}

books/templates/books/book_details.html
{% extends 'base_layout.html' %}

{% block content %}
<div class="book-detail">
    <div class="book card">
            <div class="card-body">

                <div class="row">
                    <div class="col-2">
                        <div class="w-100 h-100">
                            <img class="img-thumbnail" src="{{ book.image.url }}" alt="book-image">
                        </div>
                    </div>

                    <div class="col">
                        <div class="row">
                            <h2 class="col">{{ book.title }}</h2>

                            <div class="col-2 mt-2 fs-5 text-end">
                                {% include "review_stars.html" with rating=book.rating %}
                            </div>
                        </div>

                        <h5>{{ book.publishDate|date:"d.m.Y" }}</h5>
                    </div>
                </div>
                <div class="mt-5">
                    <p>{{ book.description }}</p>
                </div>
            </div>
    </div>
    {% include "reviews/review_create.html" with book=book form=form %}

    <div>
        <h2 class="container mt-5 mb-5 row height d-flex justify-content-center align-items-center">Opinie:</h2>
    </div>
    {% for display in display_reviews %}


<div class="card mt-4">
    <div class="card-body">
        <div class="row">
            <div class="col">
                <div class="row">
                    <h4 class="col fw-bold">{{ display.user }}</h4>

                    <div class="col-2 mt-2 fs-5 text-end">
                        {% include "review_stars.html" with rating=display.vote %}
                    </div>
                </div>
            </div>
        </div>
        <div class="mt-2">
            <p class="fs-5"><b>Recenzja: </b>{{ display.review }}</p>
        </div>
    </div>
</div>
    {% endfor %}
</div>

{% endblock %}

books/templates/books/book_list.html
{% extends 'base_layout.html' %}

{% block content %}
    <h1 class="text-center mb-4">Lista książek</h1>

    {% for book in books %}
        <div class="mb-4">
            {% include "books/book_snippet.html" with book=book %}
        </div>
    {% endfor %}

    {% include "pagination.html" with items=books %}

{% endblock %}

books/templates/books/book_not_found.html
{% extends 'base_layout.html' %}

{% block content %}
    <div class="books">
        <h1 class="text-center mb-5">Nie znaleźliśmy wyników dla frazy: {{ name }}</h1>
    </div>
{% endblock %}

books/templates/books/book_requests.html
{% extends 'base_layout.html' %}

{% block content %}
    <h1 class="text-center mb-5">Książki czekające na akceptacje</h1>
        {% if not forms %}
            <h3 class="mb-4">Brak nowych zgłoszeń</h3>
        {% endif %}

        {% for form in forms %}
            <div class="mb-4">
                {% include "books/book_snippet.html" with book=form.book book_request=True %}
            </div>
        {% endfor %}

        {% include "pagination.html" with items=forms %}
{% endblock %}

books/templates/books/book_snippet.html
{% load has_group %}

<div class="my-3 card container">
    <div class="card-body d-flex row">
        <div class="col-2">
            <div class="w-100 h-100">
                 <img class="img-thumbnail" src="{{ book.image.url }}" alt="book-image">
            </div>
        </div>
            <div class="col-10">
                <div class="row">
                    <div class="col-10">
                        <h2>
                            {% if not book_request %}
                            <a class="text-decoration-none link-secondary" href="{% url 'books:details' slug=book.slug %}">
                                {{ book.title | truncatewords:5 }}
                            </a>
                            {% endif %}

                            {% if book_request %}
                            <span>
                                {{ book.title | truncatewords:5 }}
                            </span>
                            {% endif %}
                        </h2>
                        <p>{{ book.snippet }}</p>
                    </div>
                    <div class="col text-end">
                        <p>{{ book.publishDate|date:"d.m.Y" }}</p>
                        <div class="col text-end">
                            {% include "review_stars.html" with rating=book.rating %}
                        </div>

                        {% if request.user|has_group:"admin" and not book_request %}
                        <div class="mt-3">
                            <form method="POST" action="{% url 'books:remove_book' pk=book.pk %}">
                                {% csrf_token %}
                                <button type="submit" class="btn btn-danger">Usuń</button>
                            </form>
                        </div>
                        {% endif %}

                        {% if request.user|has_group:"admin" and book_request %}
                        <div class="mt-3">
                            <form method="post" action="{% url 'books:accept' %}">
                                {% csrf_token %}
                                {{form.book_id}}
                                <button type="submit" class="btn btn-success btn-sm" style="width: 100px;">Zaakceptuj</button>
                            </form>
                            <form method="post" class="mt-2" action="{% url 'books:reject' %}">
                                {% csrf_token %}
                                {{form.book_id}}
                                <button type="submit" class="btn btn-danger btn-sm" style="width: 100px;">Odrzuć</button>
                            </form>
                        </div>
                        {% endif %}
                    </div>
            </div>
            </div>
    </div>
</div>